Repository KiOui/TOSTI, pull requests merged in 2023-09, with the labels that each got.

#497 Rewrite VueJS to use script module type
  website/orders/templates/orders/order_admin_list.html
  website/orders/templates/orders/order_admin_order.html
  website/orders/templates/orders/order_list.html
  website/orders/templates/orders/shift_admin_footer.html
  website/orders/templates/orders/shift_admin_scanner.html
  website/orders/templates/orders/shift_header.html
  website/thaliedje/templates/thaliedje/player.html
  website/thaliedje/templates/thaliedje/queue.html
  website/thaliedje/templates/thaliedje/requests.html
  website/thaliedje/templates/thaliedje/search.html
  website/tosti/templates/tosti/base.html
Labels: chore

#493 Feature/qr code scanner
  poetry.lock
  pyproject.toml
  website/orders/apps.py
  website/orders/static/orders/css/transaction-popup.css
  website/orders/static/orders/js/admin-scanner.js
  website/orders/static/orders/js/jsQR.min.js
  website/orders/static/orders/js/quagga.min.js
  website/orders/templates/orders/explainer_admin.html
  website/orders/templates/orders/explainer_deposit.html
  website/orders/templates/orders/explainer_transactions_admin.html
  website/orders/templates/orders/order_list.html
  website/orders/templates/orders/shift_admin.html
  website/orders/templates/orders/shift_admin_footer.html
  website/orders/templates/orders/shift_admin_scanner.html
  website/orders/templates/orders/shift_admin_transaction_modal.html
  website/orders/views.py
  website/tosti/api/v1/urls.py
  website/tosti/settings/base.py
  website/tosti/static/tosti/css/base.css
  website/tosti/static/tosti/css/variables.css
  website/tosti/static/tosti/js/base.js
  website/tosti/templates/tosti/base.html
  website/transactions/api/v1/serializers.py
  website/transactions/api/v1/urls.py
  website/transactions/api/v1/views.py
  website/transactions/migrations/0001_initial.py
  website/transactions/models.py
  website/users/services.py
Labels: bug, feature

#492 Fridges
  website/announcements/templatetags/__init__.py
  website/associations/api/__init__.py
  website/borrel/templatetags/__init__.py
  website/fridges/__init__.py
  website/fridges/admin.py
  website/fridges/api/__init__.py
  website/fridges/api/v1/__init__.py
  website/fridges/api/v1/urls.py
  website/fridges/api/v1/views.py
  website/fridges/apps.py
  website/fridges/migrations/0001_initial.py
  website/fridges/migrations/__init__.py
  website/fridges/models.py
  website/fridges/services.py
  website/fridges/templates/fridges/index.html
  website/fridges/urls.py
  website/fridges/views.py
  website/orders/templatetags/__init__.py
  website/thaliedje/api/__init__.py
  website/thaliedje/api/v1/__init__.py
  website/thaliedje/templatetags/__init__.py
  website/tosti/api/v1/__init__.py
  website/tosti/api/v1/urls.py
  website/tosti/management/__init__.py
  website/tosti/management/commands/__init__.py
  website/tosti/settings/base.py
  website/tosti/templates/tosti/base.html
  website/tosti/templatetags/__init__.py
  website/tosti/urls.py
  website/users/api/__init__.py
  website/users/api/v1/__init__.py
  website/venues/templatetags/__init__.py
Labels: feature

#500 Fix a bug where saving a Group would throw a 500 error
  website/users/signals.py
Labels: bug

#502 Remove importmaps everywhere
  website/orders/templates/orders/order_admin_list.html
  website/orders/templates/orders/order_list.html
  website/orders/templates/orders/shift_admin_footer.html
  website/orders/templates/orders/shift_admin_scanner.html
  website/orders/templates/orders/shift_admin_transaction_modal.html
  website/orders/templates/orders/shift_header.html
  website/thaliedje/templates/thaliedje/player.html
  website/thaliedje/templates/thaliedje/queue.html
  website/thaliedje/templates/thaliedje/requests.html
  website/thaliedje/templates/thaliedje/search.html
  website/tosti/templates/tosti/base.html
Labels: bug

#503 Fix colorblindness for red/green
  website/orders/templates/orders/order_admin_order.html
  website/orders/templates/orders/order_list.html
  website/orders/templates/orders/shift_admin_footer.html
  website/orders/templates/orders/shift_header.html
Labels: feature
